name: pattern-detection
services:
  engine:
    image: openjdk:17-jdk-alpine
    container_name: pattern-detection-engine
    volumes:
      - ../pattern-detection-engine/target/build:/app
    environment:
      - TZ=Asia/Riyadh  # Set to Riyadh timezone
      - spring.profiles.active=prod
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
    working_dir: /app
    entrypoint: >
      java -cp "./trading-bot-pattern-detection-engine.jar:./config:./lib/*" com.amdose.pattern.detection.PatternDetectionModule