# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: trading-bot
services:
  ui:
    extends:
      file: ./ui.yml
      service: portal
  broker:
    extends:
      file: ./broker.yml
      service: binance
  pattern-detection:
    extends:
      file: ./pattern-detection-engine.yml
      service: engine
