name: broker
services:
  binance:
    image: openjdk:17-jdk-alpine
    container_name: binance-broker
    network_mode: host
    volumes:
      - ~/volumes/trading-bot/broker/logs/:/tmp/trading-bot/logs/
      - ../broker-engine/target/build:/app
    environment:
      - TZ=Asia/Riyadh  # Set to Riyadh timezone
      - spring.profiles.active=prod
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
    working_dir: /app
    entrypoint: >
      java -cp "./trading-bot-broker.jar:./config:./lib/*" com.amdose.broker.engine.BrokerModule