name: pattern-detection
services:
  engine:
    image: openjdk:17-jdk-alpine
    container_name: pattern-detection-engine
    network_mode: host
    volumes:
      - ~/volumes/trading-bot/pattern-detection-engine/logs/:/tmp/trading-bot/logs/
      - ../pattern-detection-engine/target/build:/app
    environment:
      - TZ=Asia/Riyadh  # Set to Riyadh timezone
      - spring.profiles.active=prod
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
    working_dir: /app
    entrypoint: >
      java -cp "./trading-bot-pattern-detection-engine.jar:./config:./lib/*" com.amdose.pattern.detection.PatternDetectionModule