# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: trading-bot-ui
services:
  portal:
    image: openjdk:17-jdk-alpine
    container_name: ui-portal
    network_mode: host
    volumes:
      - ~/volumes/trading-bot/ui/logs/:/tmp/trading-bot-ui/logs/
      - ../ui/target/build:/app
    working_dir: /app
    ports: 
      - 8080:8080
    environment:
      - TZ=Asia/Riyadh  # Set to Riyadh timezone
      - spring.profiles.active=prod
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
    entrypoint: >
      java -cp "./trading-bot-ui.jar:./config:./lib/*" com.amdose.base.App
