spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: TRADING_BOT
    password: TRADING_BOT
    hikari.connection-timeout: 20000
    hikari.minimum-idle: 10
    hikari.maximum-pool-size: 10
    hikari.idle-timeout: 10000
    hikari.max-lifetime: 1000
    hikari.auto-commit: true
  jpa:
    show-sql: true

  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO